import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const candara = localFont({
  src: [
    {
      path: "/fonts/Candara.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "/fonts/Candara_Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "/fonts/Candara_Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "/fonts/Candara_Bold_Italic.ttf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-candara",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${candara.variable} antialiased`}>{children}</body>
    </html>
  );
}
